sudo: required
services:
  - docker
before_install:
  - docker build -t scartlex/docker-test -f Dockerfile.dev .
script:
  - docker run scartlex/docker-test npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-eu-central-1-936733129700"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
